# Generated by Django 4.1.7 on 2023-03-17 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0023_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with 9 and have exactly 10 digits.",
                        regex="^9\\d{9}$",
                    )
                ],
            ),
        ),
    ]
