# Generated by Django 4.1.7 on 2023-03-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destination", "0018_alter_places_descrption"),
    ]

    operations = [
        migrations.DeleteModel(
            name="hotel",
        ),
    ]
