# Generated by Django 4.1.7 on 2023-03-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("destination", "0019_delete_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("contact_info", models.CharField(max_length=15)),
                (
                    "nearby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="destination.places",
                    ),
                ),
            ],
        ),
    ]
